version: '3.4'

networks:
  default:
    name: url-network 
    driver: bridge
      
services:
  cache:
    image: redis:latest
    container_name: cache
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    environment:
      - REDIS_PASSWORD=
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DATABASES=0


  db:
    container_name: db
    build:
      context: .
      dockerfile: ./postgres/postgres.dockerfile
    image: "postgres-url"
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
      # uncomment the following lines to use docker volumes
#     volumes: 
#       - db:/var/lib/postgresql/data
# volumes:
#   db:
#     driver: local 